# Generated by Django 5.1.6 on 2025-02-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='degrees',
            field=models.CharField(default='Masters,Bachelors', max_length=255),
        ),
    ]
